# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

import os

import httpx

from ._core._base_client import AsyncAPIClient, SyncAPIClient
from ._core._sentinels import NotGiven, not_given
from . import resources

__all__ = ["Harbor", "AsyncHarbor"]

_DEFAULT_BASE_URL = "https://api.tryharbor.ai"


class Harbor(SyncAPIClient):
    health: resources.HealthResource
    runtime: resources.RuntimeResource

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | httpx.URL | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int = 2,
        http_client: httpx.Client | None = None,
    ) -> None:
        if api_key is None:
            api_key = os.environ.get("HARBOR_API_KEY")
        if api_key is None:
            raise ValueError(
                "The api_key client option must be set either by passing api_key "
                "to the client or by setting the HARBOR_API_KEY environment variable"
            )
        super().__init__(
            base_url=base_url or os.environ.get("HARBOR_SDK_GENERATED_BASE_URL") or _DEFAULT_BASE_URL,
            timeout=timeout,
            max_retries=max_retries,
            http_client=http_client,
            auth_headers={"Authorization": f"Bearer {api_key}"},
        )
        self.health = resources.HealthResource(self)
        self.runtime = resources.RuntimeResource(self)


class AsyncHarbor(AsyncAPIClient):
    health: resources.AsyncHealthResource
    runtime: resources.AsyncRuntimeResource

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | httpx.URL | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int = 2,
        http_client: httpx.AsyncClient | None = None,
    ) -> None:
        if api_key is None:
            api_key = os.environ.get("HARBOR_API_KEY")
        if api_key is None:
            raise ValueError(
                "The api_key client option must be set either by passing api_key "
                "to the client or by setting the HARBOR_API_KEY environment variable"
            )
        super().__init__(
            base_url=base_url or os.environ.get("HARBOR_SDK_GENERATED_BASE_URL") or _DEFAULT_BASE_URL,
            timeout=timeout,
            max_retries=max_retries,
            http_client=http_client,
            auth_headers={"Authorization": f"Bearer {api_key}"},
        )
        self.health = resources.AsyncHealthResource(self)
        self.runtime = resources.AsyncRuntimeResource(self)
