# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any

__all__ = [
    "parse_date", "parse_datetime", "is_dict", "is_list", "is_mapping",
    "PropertyInfo",
]


class PropertyInfo:
    """Annotated-metadata marker (Stainless-compatible): carries the wire
    `alias` / `format` / `discriminator` for a request-params field. Used as
    `Annotated[T, PropertyInfo(alias="wireName")]` in *Params TypedDicts.
    """

    def __init__(self, *, alias=None, format=None, discriminator=None):
        self.alias = alias
        self.format = format
        self.discriminator = discriminator

    def __repr__(self):
        kw = ", ".join(
            f"{k}={v!r}" for k, v in vars(self).items() if v is not None
        )
        return f"PropertyInfo({kw})"


def parse_datetime(value: Any) -> datetime:
    if isinstance(value, datetime):
        return value
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc)
    s = value.decode() if isinstance(value, (bytes, bytearray)) else str(value)
    if s.endswith(("Z", "z")):
        s = s[:-1] + "+00:00"
    return datetime.fromisoformat(s)


def parse_date(value: Any) -> date:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc).date()
    s = value.decode() if isinstance(value, (bytes, bytearray)) else str(value)
    return date.fromisoformat(s[:10])


def is_dict(obj: object) -> bool:
    return isinstance(obj, dict)


def is_list(obj: object) -> bool:
    return isinstance(obj, list)


def is_mapping(obj: object) -> bool:
    from collections.abc import Mapping

    return isinstance(obj, Mapping)
