import type { OrbitUiTheme, RawHtml } from './types'

export function defaultTheme(): OrbitUiTheme {
  return {
    tokens: {
      background: '0.985 0.006 80',
      foreground: '0.18 0.01 260',
      foregroundMuted: '0.52 0.015 260',
      foregroundSoft: '0.62 0.012 260',
      card: '1 0 0',
      border: '0.86 0.012 80',
      borderSubtle: '0.92 0.008 80',
      primary: '0.54 0.10 125',
      primaryForeground: '1 0 0',
      primaryHover: '0.49 0.10 125',
      muted: '0.95 0.008 80',
      radius: {
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
      },
      fontSans: "'Inter', ui-sans-serif, system-ui, sans-serif",
    },
  }
}

export function themeStyleBlock(theme?: OrbitUiTheme): RawHtml {
  const tokens = theme?.tokens ?? defaultTheme().tokens
  const css = [
    '<style data-orbit-ui-theme>',
    ':root{',
    `--background:${tokens.background};`,
    `--foreground:${tokens.foreground};`,
    `--foreground-muted:${tokens.foregroundMuted};`,
    `--foreground-soft:${tokens.foregroundSoft};`,
    `--card:${tokens.card};`,
    `--border:${tokens.border};`,
    `--border-subtle:${tokens.borderSubtle};`,
    `--primary:${tokens.primary};`,
    `--primary-foreground:${tokens.primaryForeground};`,
    `--primary-hover:${tokens.primaryHover};`,
    `--muted:${tokens.muted};`,
    `--radius-md:${tokens.radius.md};`,
    `--radius-lg:${tokens.radius.lg};`,
    `--radius-xl:${tokens.radius.xl};`,
    `--font-sans:${tokens.fontSans};`,
    '}',
    '*,*::before,*::after{box-sizing:border-box;}',
    'html{font-family:var(--font-sans);-webkit-text-size-adjust:100%;text-rendering:optimizeLegibility;}',
    'body{margin:0;min-height:100vh;font-family:var(--font-sans);background:oklch(var(--background));color:oklch(var(--foreground));}',
    'button,input,textarea,select{font:inherit;}',
    'button,[type=button],[type=submit],[type=reset]{appearance:none;}',
    'a{color:inherit;text-decoration:none;}',
    'img,svg{display:block;max-width:100%;}',
    'p,h1,h2,h3,h4,h5,h6{margin:0;}',
    'ul,ol{margin:0;padding:0;}',
    'li{list-style:none;}',
    '.bg-background{background:oklch(var(--background));}',
    '.bg-card{background:oklch(var(--card));}',
    '.bg-primary{background:oklch(var(--primary));}',
    '.bg-muted{background:oklch(var(--muted));}',
    '.text-foreground{color:oklch(var(--foreground));}',
    '.text-foreground-muted{color:oklch(var(--foreground-muted));}',
    '.text-foreground-soft{color:oklch(var(--foreground-soft));}',
    '.text-primary{color:oklch(var(--primary));}',
    '.text-primary-foreground{color:oklch(var(--primary-foreground));}',
    '.border-border{border-color:oklch(var(--border));}',
    '.border-border-subtle{border-color:oklch(var(--border-subtle));}',
    '.orbit-ui-page{min-height:100vh;padding:3rem 1.25rem;}',
    '.orbit-ui-shell{width:100%;margin:0 auto;}',
    '.orbit-ui-shell-sm{max-width:40rem;}',
    '.orbit-ui-shell-md{max-width:48rem;}',
    '.orbit-ui-shell-lg{max-width:64rem;}',
    '.orbit-ui-shell-xl{max-width:80rem;}',
    '.orbit-ui-shell-full{max-width:none;}',
    '.orbit-ui-section{padding:1.5rem 0;}',
    '.orbit-ui-section-header{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1rem;}',
    '.orbit-ui-eyebrow{font-size:.75rem;font-weight:650;letter-spacing:.12em;text-transform:uppercase;color:oklch(var(--foreground-soft));}',
    '.orbit-ui-title{font-size:clamp(2rem,5vw,4.75rem);line-height:.9;letter-spacing:-.06em;font-weight:720;color:oklch(var(--foreground));}',
    '.orbit-ui-section-title{font-size:1rem;line-height:1.2;font-weight:680;color:oklch(var(--foreground));}',
    '.orbit-ui-description{max-width:42rem;font-size:1rem;line-height:1.65;color:oklch(var(--foreground-muted));}',
    '.orbit-ui-card{border:1px solid oklch(var(--border));border-radius:var(--radius-xl);background:oklch(var(--card));box-shadow:0 1px 0 oklch(var(--border-subtle));}',
    '.orbit-ui-card-muted{background:oklch(var(--muted));}',
    '.orbit-ui-card-danger{border-color:oklch(.7 .09 30);background:oklch(.98 .018 30);}',
    '.orbit-ui-card-success{border-color:oklch(.78 .08 145);background:oklch(.97 .02 145);}',
    '.orbit-ui-field{display:grid;gap:.45rem;}',
    '.orbit-ui-label{font-size:.86rem;font-weight:620;color:oklch(var(--foreground));}',
    '.orbit-ui-input,.orbit-ui-textarea{width:100%;border:1px solid oklch(var(--border));border-radius:var(--radius-lg);background:oklch(var(--card));color:oklch(var(--foreground));outline:none;transition:border-color .16s ease,box-shadow .16s ease,background .16s ease;}',
    '.orbit-ui-input{height:2.75rem;padding:0 .85rem;}',
    '.orbit-ui-textarea{min-height:7rem;padding:.8rem .85rem;resize:vertical;}',
    '.orbit-ui-input:focus,.orbit-ui-textarea:focus{border-color:oklch(var(--primary));box-shadow:0 0 0 3px oklch(var(--primary)/.16);}',
    '.orbit-ui-help{font-size:.8rem;line-height:1.45;color:oklch(var(--foreground-soft));}',
    '.orbit-ui-error{font-size:.8rem;line-height:1.45;color:oklch(.55 .14 30);}',
    '.orbit-ui-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;border:1px solid transparent;border-radius:999px;font-weight:680;line-height:1;white-space:nowrap;cursor:pointer;transition:background .16s ease,border-color .16s ease,color .16s ease,transform .16s ease;}',
    '.orbit-ui-button:active{transform:translateY(1px);}',
    '.orbit-ui-button[disabled]{opacity:.5;cursor:not-allowed;transform:none;}',
    '.orbit-ui-button-sm{height:2.1rem;padding:0 .8rem;font-size:.82rem;}',
    '.orbit-ui-button-md{height:2.65rem;padding:0 1.05rem;font-size:.9rem;}',
    '.orbit-ui-button-lg{height:3.05rem;padding:0 1.3rem;font-size:1rem;}',
    '.orbit-ui-button-primary{background:oklch(var(--primary));color:oklch(var(--primary-foreground));}',
    '.orbit-ui-button-primary:hover{background:oklch(var(--primary-hover));}',
    '.orbit-ui-button-outline{border-color:oklch(var(--border));background:transparent;color:oklch(var(--foreground));}',
    '.orbit-ui-button-outline:hover{background:oklch(var(--muted));}',
    '.orbit-ui-button-ghost{background:transparent;color:oklch(var(--foreground-muted));}',
    '.orbit-ui-button-ghost:hover{background:oklch(var(--muted));color:oklch(var(--foreground));}',
    '.orbit-ui-button-danger{background:oklch(.56 .16 30);color:white;}',
    '.orbit-ui-button-danger:hover{background:oklch(.5 .16 30);}',
    '</style>',
  ].join('')

  return {
    $$orbit_ui_raw: true,
    html: css,
  }
}
