# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class HealthRetrieveDeepResponseChecks(BaseModel):
    db: Literal['ok', 'error']
    migrations: Literal['ok', 'drift', 'unknown']


class HealthRetrieveDeepResponseMigrations(BaseModel):
    applied_count: Optional[float] = None
    expected: Optional[Union[str, None]] = None
    latest_applied: Optional[Union[str, None]] = None
    latest_applied_at: Optional[Union[str, None]] = None


class HealthRetrieveDeepResponse(BaseModel):
    checks: HealthRetrieveDeepResponseChecks
    db_ms: float
    environment: str
    error: Optional[str] = None
    migrations: HealthRetrieveDeepResponseMigrations
    service: Literal['harbor-api']
    status: Literal['ok', 'error']
    timestamp: datetime
    total_ms: float
    version: Optional[Union[str, None]] = None
