# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class RuntimeExecuteParamsExecutionInputs(BaseModel):
    content_type: Optional[str] = None
    data_base64: str
    path: str
    sha256: str
    size_bytes: float


class RuntimeExecuteParamsSources(BaseModel):
    namespace: str


class RuntimeExecuteParams(TypedDict, total=False):
    code: str
    execution_inputs: List[RuntimeExecuteParamsExecutionInputs]
    mode: Literal['exec', 'workflow']
    origin_cwd: str
    run_id: str
    sand_session_id: str
    sources: List[RuntimeExecuteParamsSources]
    timeout_ms: float
    workspace_id: str
