# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class RuntimeExecuteResponseDataContentVariant0(BaseModel):
    mime_type: Optional[str] = None
    text: str
    type: Literal['text']


class RuntimeExecuteResponseDataContentVariant1(BaseModel):
    json_: object = Field(alias="json")
    mime_type: Optional[str] = None
    type: Literal['json']


class RuntimeExecuteResponseDataContentVariant2SkillFile(BaseModel):
    content_base64: str
    content_hash: str
    relative_path: str


class RuntimeExecuteResponseDataContentVariant2Skill(BaseModel):
    content: str
    content_hash: str
    description: Optional[str] = None
    files: Optional[List[RuntimeExecuteResponseDataContentVariant2SkillFile]] = None
    name: Optional[str] = None
    slug: str
    source_commit: Optional[str] = None


class RuntimeExecuteResponseDataContentVariant2(BaseModel):
    skill: RuntimeExecuteResponseDataContentVariant2Skill
    type: Literal['skill_bundle']


class RuntimeExecuteResponseDataWarning(BaseModel):
    message: str
    namespace: str
    tool: str


class RuntimeExecuteResponseData(BaseModel):
    content: Optional[List[Union[RuntimeExecuteResponseDataContentVariant0, RuntimeExecuteResponseDataContentVariant1, RuntimeExecuteResponseDataContentVariant2]]] = None
    error: Optional[str] = None
    logs: Optional[object] = None
    mode: Literal['dynamic_worker', 'workflow']
    result: object
    run_id: str
    warnings: Optional[List[RuntimeExecuteResponseDataWarning]] = None
    workflow_instance_id: Optional[str] = None


class RuntimeExecuteResponse(BaseModel):
    data: RuntimeExecuteResponseData
    success: Literal[True]
