# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property

import httpx

from harbor_sdk_generated._core._request_options import make_request_options
from harbor_sdk_generated._core._resource import AsyncAPIResource, SyncAPIResource
from harbor_sdk_generated._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from harbor_sdk_generated._core._sentinels import NotGiven, not_given
from harbor_sdk_generated._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from harbor_sdk_generated.types import HealthRetrieveDeepResponse, HealthRetrieveResponse

__all__ = ["HealthResource", "AsyncHealthResource"]


class HealthResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> HealthResourceWithRawResponse:
        return HealthResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> HealthResourceWithStreamingResponse:
        return HealthResourceWithStreamingResponse(self)

    def retrieve(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> HealthRetrieveResponse:
        """Read the shallow Harbor API health status."""
        return self._get(
            f"/health",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=HealthRetrieveResponse,
        )

    def retrieve_deep(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> HealthRetrieveDeepResponse:
        """Read the deep Harbor API health status including D1 migration readiness."""
        return self._get(
            f"/healthz",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=HealthRetrieveDeepResponse,
        )


class AsyncHealthResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncHealthResourceWithRawResponse:
        return AsyncHealthResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncHealthResourceWithStreamingResponse:
        return AsyncHealthResourceWithStreamingResponse(self)

    async def retrieve(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> HealthRetrieveResponse:
        """Read the shallow Harbor API health status."""
        return await self._get(
            f"/health",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=HealthRetrieveResponse,
        )

    async def retrieve_deep(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> HealthRetrieveDeepResponse:
        """Read the deep Harbor API health status including D1 migration readiness."""
        return await self._get(
            f"/healthz",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=HealthRetrieveDeepResponse,
        )


class HealthResourceWithRawResponse:
    def __init__(self, health: HealthResource) -> None:
        self.retrieve = to_raw_response_wrapper(health.retrieve)
        self.retrieve_deep = to_raw_response_wrapper(health.retrieve_deep)


class AsyncHealthResourceWithRawResponse:
    def __init__(self, health: AsyncHealthResource) -> None:
        self.retrieve = async_to_raw_response_wrapper(health.retrieve)
        self.retrieve_deep = async_to_raw_response_wrapper(health.retrieve_deep)


class HealthResourceWithStreamingResponse:
    def __init__(self, health: HealthResource) -> None:
        self.retrieve = to_streamed_response_wrapper(health.retrieve)
        self.retrieve_deep = to_streamed_response_wrapper(health.retrieve_deep)


class AsyncHealthResourceWithStreamingResponse:
    def __init__(self, health: AsyncHealthResource) -> None:
        self.retrieve = async_to_streamed_response_wrapper(health.retrieve)
        self.retrieve_deep = async_to_streamed_response_wrapper(health.retrieve_deep)
