# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import List, Literal

import httpx

from harbor_sdk_generated._core._request_options import make_request_options
from harbor_sdk_generated._core._resource import AsyncAPIResource, SyncAPIResource
from harbor_sdk_generated._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from harbor_sdk_generated._core._sentinels import NotGiven, not_given
from harbor_sdk_generated._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from harbor_sdk_generated._core._models import to_jsonable
from harbor_sdk_generated.types import RuntimeExecuteParamsExecutionInputs, RuntimeExecuteParamsSources, RuntimeExecuteResponse

__all__ = ["RuntimeResource", "AsyncRuntimeResource"]


class RuntimeResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RuntimeResourceWithRawResponse:
        return RuntimeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RuntimeResourceWithStreamingResponse:
        return RuntimeResourceWithStreamingResponse(self)

    def execute(
        self,
        *,
        code: str,
        workspace_id: str,
        execution_inputs: List[RuntimeExecuteParamsExecutionInputs] | NotGiven = not_given,
        mode: Literal['exec', 'workflow'] | NotGiven = not_given,
        origin_cwd: str | NotGiven = not_given,
        run_id: str | NotGiven = not_given,
        sand_session_id: str | NotGiven = not_given,
        sources: List[RuntimeExecuteParamsSources] | NotGiven = not_given,
        timeout_ms: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RuntimeExecuteResponse:
        """The API control plane authenticates and authorizes the caller before dispatching to the runtime execution layer."""
        _body = {
            "code": code,
            "execution_inputs": execution_inputs,
            "mode": mode,
            "origin_cwd": origin_cwd,
            "run_id": run_id,
            "sand_session_id": sand_session_id,
            "sources": sources,
            "timeout_ms": timeout_ms,
            "workspace_id": workspace_id,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return self._post(
            f"/plugins/execute",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RuntimeExecuteResponse,
        )


class AsyncRuntimeResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRuntimeResourceWithRawResponse:
        return AsyncRuntimeResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRuntimeResourceWithStreamingResponse:
        return AsyncRuntimeResourceWithStreamingResponse(self)

    async def execute(
        self,
        *,
        code: str,
        workspace_id: str,
        execution_inputs: List[RuntimeExecuteParamsExecutionInputs] | NotGiven = not_given,
        mode: Literal['exec', 'workflow'] | NotGiven = not_given,
        origin_cwd: str | NotGiven = not_given,
        run_id: str | NotGiven = not_given,
        sand_session_id: str | NotGiven = not_given,
        sources: List[RuntimeExecuteParamsSources] | NotGiven = not_given,
        timeout_ms: float | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RuntimeExecuteResponse:
        """The API control plane authenticates and authorizes the caller before dispatching to the runtime execution layer."""
        _body = {
            "code": code,
            "execution_inputs": execution_inputs,
            "mode": mode,
            "origin_cwd": origin_cwd,
            "run_id": run_id,
            "sand_session_id": sand_session_id,
            "sources": sources,
            "timeout_ms": timeout_ms,
            "workspace_id": workspace_id,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return await self._post(
            f"/plugins/execute",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RuntimeExecuteResponse,
        )


class RuntimeResourceWithRawResponse:
    def __init__(self, runtime: RuntimeResource) -> None:
        self.execute = to_raw_response_wrapper(runtime.execute)


class AsyncRuntimeResourceWithRawResponse:
    def __init__(self, runtime: AsyncRuntimeResource) -> None:
        self.execute = async_to_raw_response_wrapper(runtime.execute)


class RuntimeResourceWithStreamingResponse:
    def __init__(self, runtime: RuntimeResource) -> None:
        self.execute = to_streamed_response_wrapper(runtime.execute)


class AsyncRuntimeResourceWithStreamingResponse:
    def __init__(self, runtime: AsyncRuntimeResource) -> None:
        self.execute = async_to_streamed_response_wrapper(runtime.execute)
